#!/bin/bash

echo "Running pre-commit hook"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

#Make sure it builds first - we're not big enough for CI 

#float up in MECAT until you're in root dir 
while [ "basename $(realpath $(dirname .))" -ne "MECAT" ]; do
    cd ..
done

#compile test
make -j 8
if [ $? -ne 0 ]; then
    echo "Make failed. Commit aborted" 
    exit 1
fi

#output validity test

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
